from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Mood:
    """Mood."""

    name: str
    bpm: float
    drum_density: float  # 0..1 hats/kick extras
    arp_prob: float  # probability the arp layer plays in a section
    lead_prob: float  # probability of a lead phrase per chorus bar
    brightness: float  # multiplier applied to filter cutoffs
    major_prob: float  # probability of a major key
    progressions: dict[str, float] = field(default_factory=dict)
    scale: str = "minor"  # minor | major | phrygian | harmonic_minor
    sevenths: bool = True  # stack a 7th on every chord
    halftime: bool = False  # snare on beat 3 only
    pad_octave: int = 4
    patches: dict[str, str] = field(default_factory=dict)  # layer -> patch name
    pools: dict[str, list[str]] = field(default_factory=dict)  # layer -> patches per section
    bass_styles: dict[str, float] = field(default_factory=dict)  # style -> weight
    bpm_range: tuple[float, float] = (100.0, 118.0)  # tempo drawn here at start / transitions
    snap_prob: float = 0.0  # finger snaps on the backbeat (per section)
    ride_prob: float = 0.0  # ride cymbal instead of closed hats (per section)
    shaker_prob: float = 0.0  # 16th-note shaker (per section)
    tick_prob: float = 0.5  # dry closed hat "tic tic" on the 8ths (per section)
    straight: bool = False  # eighties groove: dead on the 4/4 grid, no random kick/hat/roll
    mono_drums: bool = False  # minimal: only one of kick/snare/hat per section (programming focus)


DARK_PATCHES = {
    "drums": "drums_dark",
    "bass": "bass_dark",
    "arp": "arp_dark",
    "pad": "pad_dark",
    "lead": "lead_dark",
    "lead2": "lead_hollow",
    "ambient": "ambient_dark",
}
DARK_POOLS = {
    "bass": [
        "bass_dark",
        "bass_industrial",
        "bass_sub",
        "bass_growl",
        "bass_reese",
        "bass_fm",
        "bass_wobble",
        "bass_808",
        "bass_ms20",
        "bass_sh101",
        "bass_dx7",
    ],
    "lead": [
        "lead_dark",
        "lead_industrial",
        "lead_scream",
        "lead_growl",
        "lead_glide",
        "lead_ms20",
        "lead_minimoog",
        "lead_cs80",
        "lead_sh101",
        "lead_arp2600",
        "lead_odyssey",
        "lead_pro_one",
        "lead_memorymoog",
        "lead_d50",
        "lead_sem",
        "lead_piano_atmos",
    ],
    "lead2": [  # second voice: softer patches that sit under the theme
        "lead_hollow",
        "lead_organ",
        "lead_polysix",
        "lead_sem",
        "lead_piano_atmos",
        "lead_memorymoog",
    ],
    "pad": [
        "pad_dark",
        "pad_warm",
        "pad_choir",
        "pad_strings",
        "pad_cs80",
        "pad_obx",
        "pad_piano_atmos",
        "solina_strings",
        "solina_cello",
        "solina_wywh",
        "solina_dry",
        "solina_contrabass",
    ],
    "arp": [
        "arp_dark",
        "arp_stab",
        "arp_fm",
        "arp_square",
        "arp_sh101",
        "arp_dx7",
        "arp_piano_atmos",
    ],
    "ambient": [
        "ambient_dark",
        "ambient_deep",
        "ambient_wind",
        "ambient_choir",
        "ambient_vhs",
        "ambient_bells",
        "ambient_tape",
        "solina_oxygene",
    ],
    "drums": [
        "drums_dark",
        "drums_industrial",
        "drums_hall",
        "drums_lofi",
        "drums_breaks",
        "drums_acoustic",
    ],
}
BRIGHT_POOLS = {
    "bass": [
        "bass_moog",
        "bass_sub",
        "bass_pulse",
        "bass_reese",
        "bass_square",
        "bass_pluck",
        "bass_fm",
        "bass_808",
        "bass_prophet",
        "bass_sh101",
        "bass_dx7",
    ],
    "lead": [
        "lead_saw",
        "lead_pulse",
        "lead_industrial",
        "lead_brass",
        "lead_hollow",
        "lead_glide",
        "lead_organ",
        "lead_prophet",
        "lead_obx",
        "lead_cs80",
        "lead_minimoog",
        "lead_jupiter",
        "lead_juno",
        "lead_dx7",
        "lead_polysix",
        "lead_m1",
        "lead_jx8p",
        "lead_synthex",
        "lead_d50",
        "lead_piano_atmos",
    ],
    "lead2": [  # second voice: softer patches that sit under the theme
        "lead_hollow",
        "lead_juno",
        "lead_polysix",
        "lead_organ",
        "lead_m1",
        "lead_piano_atmos",
        "lead_jx8p",
        "solina_horn",
        "solina_trumpet",
        "solina_radio_star",
    ],
    "pad": [
        "pad_juno",
        "pad_strings",
        "pad_glass",
        "pad_shimmer",
        "pad_warm",
        "pad_prophet",
        "pad_jupiter",
        "pad_obx",
        "pad_cs80",
        "pad_polysix",
        "pad_piano_atmos",
        "solina_strings",
        "solina_full",
        "solina_moon_safari",
        "solina_dream_weaver",
        "solina_violin",
        "solina_viola",
    ],
    "arp": [
        "arp_pluck",
        "arp_saw",
        "arp_square",
        "arp_glass",
        "arp_fm",
        "arp_jupiter",
        "arp_sh101",
        "arp_dx7",
        "arp_piano_atmos",
    ],
    "ambient": [
        "ambient_drone",
        "ambient_shimmer",
        "ambient_rain",
        "ambient_choir",
        "ambient_wind",
        "ambient_glass",
        "ambient_ocean",
        "ambient_neon",
        "ambient_tape",
    ],
    "drums": [  # dry, pure kits only: no delay, no breakbeat, for the straight eighties groove
        "drums_808",
        "drums_linn",
        "drums_dmx",
        "drums_tight",
        "drums_acoustic",
        "drums_soft80",
    ],
}
DARK_BASS = {"eighths": 2, "riff": 3, "sixteenths": 2, "syncopated": 1, "octaves": 1}
BRIGHT_BASS = {"eighths": 3, "octaves": 2, "syncopated": 1, "walk": 1, "sixteenths": 1}

CYBER_POOLS = {
    "bass": [
        "bass_industrial",
        "bass_growl",
        "bass_reese",
        "bass_industrial",
        "bass_wobble",
        "bass_fm",
        "bass_acid",
        "bass_ms20",
    ],
    "lead": [
        "lead_industrial",
        "lead_scream",
        "lead_dark",
        "lead_growl",
        "lead_ms20",
        "lead_arp2600",
        "lead_odyssey",
        "lead_sh101",
        "lead_memorymoog",
        "lead_dx7",
    ],
    "lead2": [  # second voice: softer patches that sit under the theme
        "lead_hollow",
        "lead_sem",
        "lead_organ",
        "lead_dx7",
    ],
    "pad": ["pad_dark", "pad_shimmer", "pad_glass", "pad_prophet"],
    "arp": ["arp_stab", "arp_fm", "arp_dark", "arp_square", "arp_sh101"],
    "ambient": ["ambient_dark", "ambient_rain", "ambient_deep", "ambient_vhs", "ambient_neon"],
    "drums": ["drums_industrial", "drums_dark", "drums_lofi", "drums_tight"],
}
CYBER_BASS = {"sixteenths": 3, "riff": 3, "eighths": 2, "octaves": 1}
DRIVE_POOLS = {
    "bass": [
        "bass_moog",
        "bass_sub",
        "bass_pulse",
        "bass_reese",
        "bass_square",
        "bass_fm",
        "bass_acid",
        "bass_sh101",
        "bass_prophet",
    ],
    "lead": [
        "lead_saw",
        "lead_pulse",
        "lead_scream",
        "lead_brass",
        "lead_glide",
        "lead_obx",
        "lead_prophet",
        "lead_jupiter",
        "lead_juno",
        "lead_jx8p",
        "lead_synthex",
        "lead_pro_one",
        "lead_polysix",
    ],
    "lead2": [  # second voice: softer patches that sit under the theme
        "lead_hollow",
        "lead_juno",
        "lead_polysix",
        "lead_jx8p",
        "lead_m1",
    ],
    "pad": ["pad_juno", "pad_strings", "pad_shimmer", "pad_jupiter", "pad_obx"],
    "arp": ["arp_saw", "arp_pluck", "arp_stab", "arp_square", "arp_jupiter", "arp_sh101"],
    "ambient": [
        "ambient_shimmer",
        "ambient_drone",
        "ambient_wind",
        "ambient_neon",
        "ambient_glass",
        "ambient_ocean",
    ],
    "drums": ["drums_808", "drums_linn", "drums_dmx", "drums_tight", "drums_soft80"],
}
DRIVE_BASS = {"eighths": 3, "sixteenths": 3, "octaves": 2, "syncopated": 1}
CHILL_BASS = {"eighths": 2, "walk": 3, "syncopated": 2, "octaves": 1}
MINIMAL_BASS = {"eighths": 4, "octaves": 3, "syncopated": 1}
MINIMAL_POOLS = {
    "bass": [
        "bass_sub",
        "bass_pulse",
        "bass_moog",
        "bass_808",
        "bass_pluck",
        "bass_sh101",
        "bass_dub",
        "bass_thump",
        "bass_juno60",
        "bass_soft",
        "dx7_bass",
    ],
    "lead": [
        "lead_hollow",
        "lead_organ",
        "lead_juno",
        "lead_polysix",
        "lead_piano_atmos",
        "lead_m1",
    ],
    "lead2": [
        "lead_hollow",
        "lead_organ",
        "lead_polysix",
        "lead_piano_atmos",
    ],
    "pad": [
        "pad_warm",
        "pad_dark",
        "pad_polysix",
        "pad_piano_atmos",
        "pad_shimmer",
        "dx7_epiano",
    ],
    "arp": [
        "arp_pluck",
        "arp_square",
        "arp_glass",
        "arp_piano_atmos",
    ],
    "ambient": [
        "ambient_drone",
        "ambient_tape",
        "ambient_wind",
        "ambient_dark",
        "ambient_choir",
        "dx7_bell",
    ],
    "drums": [
        "drums_tight",
        "drums_808",
        "drums_linn",
        "drums_acoustic",
        "drums_soft80",
    ],
}
MINIMAL_PATCHES = {
    "drums": "drums_tight",
    "bass": "bass_sub",
    "arp": "arp_pluck",
    "pad": "pad_warm",
    "lead": "lead_hollow",
    "lead2": "lead_hollow",
    "ambient": "ambient_drone",
}

MOODS: dict[str, Mood] = {
    "dark": Mood(
        "dark",
        92,
        0.35,
        0.45,
        0.2,
        0.6,
        0.0,
        {
            "i-bII-i-bII": 3,
            "i-iv-bII-i": 3,
            "i-bVI-bII-i": 2,
            "i-bvii-bVI-bII": 2,
            "i-i-bVI-bII": 2,
            "i-iv-i-bII": 2,
        },
        scale="phrygian",
        sevenths=False,
        halftime=True,
        pad_octave=3,
        patches=DARK_PATCHES,
        pools=DARK_POOLS,
        bass_styles=DARK_BASS,
        bpm_range=(82.0, 100.0),
        tick_prob=0.4,
    ),
    "noir": Mood(
        "noir",
        96,
        0.4,
        0.5,
        0.3,
        0.7,
        0.0,
        {"i-VI-V-i": 3, "i-iv-V-i": 3, "i-iv-VI-V": 2, "i-i-VI-V": 2, "i-VI-III-VII": 1},
        scale="harmonic_minor",
        sevenths=False,
        halftime=True,
        pad_octave=3,
        patches=DARK_PATCHES,
        pools=DARK_POOLS,
        bass_styles=DARK_BASS,
        bpm_range=(86.0, 104.0),
        tick_prob=0.6,
        snap_prob=0.5,
        ride_prob=0.3,
    ),
    "dreamy": Mood(
        "dreamy",
        108,
        0.5,
        0.75,
        0.4,
        1.0,
        0.35,
        {
            "i-VI-III-VII": 3,
            "i-VII-VI-VII": 2,
            "i-iv-VI-V": 1,
            "i-VI-VII-i": 2,
            "VI-VII-i-i": 2,
            "i-III-VII-VI": 2,
            "iv-VI-i-VII": 1,
        },
        pools=BRIGHT_POOLS,
        bass_styles=BRIGHT_BASS,
        bpm_range=(98.0, 114.0),
        tick_prob=0.6,
        snap_prob=0.4,
        ride_prob=0.3,
        shaker_prob=0.3,
        straight=True,
    ),
    "outrun": Mood(
        "outrun",
        118,
        0.85,
        0.95,
        0.55,
        1.2,
        0.1,
        {
            "i-VI-III-VII": 3,
            "i-VII-VI-VII": 3,
            "i-iv-VI-V": 2,
            "i-VI-VII-i": 2,
            "VI-VII-i-i": 2,
            "i-III-VII-VI": 1,
            "iv-VI-i-VII": 1,
        },
        pools=BRIGHT_POOLS,
        bass_styles=BRIGHT_BASS,
        bpm_range=(110.0, 128.0),
        ride_prob=0.3,
        straight=True,
    ),
    "cyberpunk": Mood(
        "cyberpunk",
        124,
        0.9,
        0.9,
        0.5,
        0.8,
        0.0,
        {
            "i-bII-i-bII": 2,
            "i-iv-bII-i": 2,
            "i-VI-VII-i": 2,
            "i-VII-VI-VII": 2,
            "i-v-VI-iv": 2,
            "i-iv-i-VI": 1,
            "i-VI-iv-VII": 2,
        },
        scale="minor",
        sevenths=False,
        halftime=False,
        pad_octave=3,
        patches=DARK_PATCHES,
        pools=CYBER_POOLS,
        bass_styles=CYBER_BASS,
        bpm_range=(118.0, 132.0),
        tick_prob=0.3,
    ),
    "horror": Mood(
        "horror",
        72,
        0.2,
        0.3,
        0.15,
        0.5,
        0.0,
        {"i-bII-bv-i": 3, "i-biii-bII-i": 2, "i-bII-bVI-bv": 2, "i-bII-i-bII": 2},
        scale="locrian",
        sevenths=False,
        halftime=True,
        pad_octave=3,
        patches=DARK_PATCHES,
        pools=DARK_POOLS,
        bass_styles=DARK_BASS,
        bpm_range=(66.0, 80.0),
        tick_prob=0.3,
    ),
    "desert": Mood(
        "desert",
        96,
        0.45,
        0.6,
        0.35,
        0.7,
        0.0,
        {"I-bII-I-bvii": 3, "I-iv-bII-I": 3, "I-bVI-bvii-I": 2, "i-bII-i-bII": 1},
        scale="phrygian_dominant",
        sevenths=False,
        halftime=True,
        pad_octave=3,
        patches=DARK_PATCHES,
        pools=DARK_POOLS,
        bass_styles=DARK_BASS,
        bpm_range=(88.0, 104.0),
        shaker_prob=0.5,
        snap_prob=0.2,
    ),
    "chill": Mood(
        "chill",
        90,
        0.4,
        0.6,
        0.3,
        0.9,
        0.0,
        {"i-IV-i-IV": 3, "i-bVII-IV-i": 2, "i-ii-bIII-ii": 2, "i-IV-bVII-i": 2, "i-ii-IV-i": 1},
        scale="dorian",
        sevenths=True,
        halftime=False,
        pad_octave=4,
        pools=BRIGHT_POOLS,
        bass_styles=CHILL_BASS,
        bpm_range=(84.0, 96.0),
        tick_prob=0.8,
        snap_prob=0.8,
        ride_prob=0.4,
        shaker_prob=0.6,
        straight=True,
    ),
    "retro": Mood(
        "retro",
        110,
        0.6,
        0.8,
        0.45,
        1.1,
        0.5,
        {
            "I-V-vi-IV": 3,
            "vi-IV-I-V": 3,
            "I-vi-IV-V": 2,
            "IV-I-V-vi": 1,
            "I-bVII-IV-I": 2,
            "I-IV-bVII-IV": 2,
            "I-v-bVII-IV": 1,
        },
        scale="mixolydian",
        sevenths=True,
        halftime=False,
        pad_octave=4,
        pools=BRIGHT_POOLS,
        bass_styles=BRIGHT_BASS,
        bpm_range=(104.0, 118.0),
        tick_prob=0.8,
        snap_prob=0.35,
        ride_prob=0.5,
        shaker_prob=0.2,
        straight=True,
    ),
    "drive": Mood(
        "drive",
        128,
        1.0,
        1.0,
        0.5,
        1.2,
        0.0,
        {
            "i-VI-III-VII": 3,
            "i-VII-VI-VII": 3,
            "i-VI-VII-i": 2,
            "VI-VII-i-i": 2,
            "i-VII-III-VI": 2,
            "VI-i-VII-III": 1,
            "i-III-iv-VI": 1,
        },
        scale="minor",
        sevenths=True,
        halftime=False,
        pad_octave=4,
        pools=DRIVE_POOLS,
        bass_styles=DRIVE_BASS,
        bpm_range=(122.0, 136.0),
        tick_prob=0.4,
        ride_prob=0.35,
        straight=True,
    ),
    "minimal": Mood(
        "minimal",
        96,
        0.18,
        0.22,
        0.1,
        0.7,
        0.0,
        {
            "i-IV-i-IV": 4,
            "I-IV-I-IV": 3,
            "i-bVII-IV-i": 2,
            "I-IV-bVII-I": 1,
        },
        scale="dorian",
        sevenths=False,
        halftime=False,
        pad_octave=4,
        patches=MINIMAL_PATCHES,
        pools=MINIMAL_POOLS,
        bass_styles=MINIMAL_BASS,
        bpm_range=(90.0, 108.0),
        snap_prob=0.0,
        ride_prob=0.0,
        shaker_prob=0.0,
        tick_prob=0.0,
        straight=True,
        mono_drums=True,
    ),
    "programming": Mood(
        "programming",
        94,
        0.14,
        0.18,
        0.08,
        0.65,
        0.0,
        {
            "i-IV-i-IV": 4,
            "I-IV-I-IV": 3,
            "i-IV-bVII-i": 2,
            "i-bVII-IV-i": 1,
        },
        scale="minor",
        sevenths=False,
        halftime=False,
        pad_octave=4,
        patches=MINIMAL_PATCHES,
        pools=MINIMAL_POOLS,
        bass_styles=MINIMAL_BASS,
        bpm_range=(88.0, 104.0),
        snap_prob=0.0,
        ride_prob=0.0,
        shaker_prob=0.0,
        tick_prob=0.0,
        straight=True,
        mono_drums=True,
    ),
}
